=== giellalt/dict-nob-fkv/script/nobfkv.dtd
<!--
Planar
Norsk oppslagsord
norsk ordklasse 

Kvensk omsetjing
Stammeklasse
Stamme+
-->
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >


<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>

<!-- the header -->
<!ELEMENT e (l, mg+, syng*, refg*, comm?) >

<!ELEMENT l (#PCDATA) >
<!ATTLIST l 
		    decl ( f | fx | f1 | f1x | f2 | f3 | fpl |
  m | mx | mo | m1 | m1b | mix | m2 | m3 | m3x | m4 | mpl |
  n | nx | no | n1 | n1b | n2 | n2c | n3 | n3b | n3c | n4 | n4b | npl | 
  v | num | pr | adv | cs | cc | i |
  ax | a | a1 | a2 | a3 | a4 | a5 | apl | det | pron | x ) #IMPLIED
           type (ord) #IMPLIED
 >

<!--
Kodane er frå finsk-norsk ordbok.
Koden x er plasshaldar når det ikkje er kode der.
-->

<!ELEMENT mg (tg+)>
<!ELEMENT tg (re?, (t, stem*)+, xg*)>

<!ELEMENT re (#PCDATA) >
<!ELEMENT t (#PCDATA) >
<!ATTLIST t 
      pos ( proa | a | adv | apl | cc | i | cs | det | n | npl | num | pr | po |pron | v | x ) #IMPLIED
      decl ( 1 | 2 | x ) #IMPLIED
      geo ( eva | por | rai | pva) #IMPLIED 
>      

<!ELEMENT stem (#PCDATA)>

<!ELEMENT xg (x, xt)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT xt (#PCDATA)>

<!ELEMENT syng (syn+)>
<!ELEMENT syn (#PCDATA)>

<!ELEMENT refg (ref+)>

<!ELEMENT comm (#PCDATA)>

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-nob-fkv/src/v_nobfkv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r PUBLIC "-//XMLmind//DTD nobfkv//FI" "../script/nobfkv.dtd">
<?xml-stylesheet type="text/css" href="../script/nobfkv.css"?>
<r xmlns:xhtml="http://www.w3.org/1999/xhtml">
   <lics xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT,
          Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <l pos="V">adlyde</l>
      <mg>
         <tg>
            <t pos="V">kuunnella</t>
            <stem>kuunnele-</stem>
            <stem>kuuntel-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">advare</l>
      <mg>
         <tg>
            <t pos="V">varottaat</t>
            <stem>varota-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">akte</l>
      <mg>
         <tg>
            <t pos="V">aikkoot</t>
            <stem>aio-</stem>
            <stem>aiko-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">ane</l>
      <mg>
         <tg>
            <t pos="V">aavistaat</t>
            <stem>aavista-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">angre</l>
      <mg>
         <tg>
            <t pos="V">kattuut</t>
            <stem>kađu-</stem>
            <stem>katu-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">angripe</l>
      <mg>
         <tg>
            <t pos="V">hyökätä</t>
            <stem>hyökkää-</stem>
            <stem>hyökän-</stem>
         </tg>
         <tg>
            <t pos="V">karistaat</t>
         </tg>
         <tg>
            <t pos="V">karssiit jonku pääle</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">anstrenges</l>
      <mg>
         <tg>
            <t pos="V">rasittaat</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">anta</l>
      <mg>
         <tg>
            <t pos="V">arvela</t>
            <stem>arvele-</stem>
            <stem>arvel-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">luulla</t>
            <stem>luule-</stem>
            <stem>lul-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">anvende</l>
      <mg>
         <tg>
            <t pos="V">käyttäät</t>
            <stem>käytä-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">arbeide</l>
      <mg>
         <tg>
            <t pos="V">työtellä</t>
            <stem>työtele-</stem>
            <stem>työtel-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">hommata</t>
            <stem>hommaa-</stem>
            <stem>homman-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">arve</l>
      <mg>
         <tg>
            <t pos="V">perriit</t>
            <stem>peri-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">attestere</l>
      <mg>
         <tg>
            <t pos="V">tođistaat</t>
            <stem>tođista-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">avfyre</l>
      <mg>
         <tg>
            <t pos="V">laukasta</t>
            <stem>laukase-</stem>
            <stem>laukas-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">avkjøle</l>
      <mg>
         <tg>
            <t pos="V">jähđyttäät</t>
            <stem>jähđytä-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">avslutte</l>
      <mg>
         <tg>
            <t pos="V">lopettaat</t>
            <stem>lopeta-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">lopetella</t>
            <stem>lopettele-</stem>
            <stem>lopetel-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">avsluttes</l>
      <mg>
         <tg>
            <t pos="V">päättyyt</t>
            <stem>pääty-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">bade</l>
      <mg>
         <tg>
            <t pos="V">hauttoot</t>
            <stem>hauđo-</stem>
            <stem>hauto-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">saunoot</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">banke</l>
      <mg>
         <tg>
            <t pos="V">takkoot</t>
            <stem>tao-</stem>
            <stem>tako-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">banne</l>
      <mg>
         <tg>
            <t pos="V">kirota</t>
            <stem>kirroo-</stem>
            <stem>kiron-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">lähätellä</t>
            <stem>lähättele-</stem>
            <stem>lähätel-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">barke</l>
      <mg>
         <tg>
            <t pos="V">parkita</t>
            <stem>parkkitte-</stem>
            <stem>parkitten-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">be</l>
      <mg>
         <tg>
            <t pos="V">rukkoilla</t>
            <stem>rukkoile-</stem>
            <stem>rukkoil-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">käskeet</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">kuttuut</t>
            <stem>kuttu-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">bebreide</l>
      <mg>
         <tg>
            <t pos="V">moittiit</t>
            <stem>moiti-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">befri</l>
      <mg>
         <tg>
            <t pos="V">vaphauttaat</t>
            <stem>vaphauta-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">päästäät</t>
            <stem>päästä-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">begrave</l>
      <mg>
         <tg>
            <t pos="V">hauđata</t>
            <stem>hauttaa-</stem>
            <stem>hauđan-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">begrense</l>
      <mg>
         <tg>
            <t pos="V">rajottaat</t>
            <stem>rajota-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">begynne</l>
      <mg>
         <tg>
            <t pos="V">alkkaat</t>
            <stem>ala-</stem>
            <stem>alka-</stem>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">alottaat</t>
            <stem>alota-</stem>
            <stem>alotta-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">behøve</l>
      <mg>
         <tg>
            <t pos="V">tarvita</t>
            <stem>tarvitte-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">bekjenne</l>
      <mg>
         <tg>
            <t pos="V">tunnustaat</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">beklage</l>
      <mg>
         <tg>
            <t pos="V">pahotella</t>
            <stem>pahottele-</stem>
            <stem>pahotel-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">bekoste</l>
      <mg>
         <tg>
            <t pos="V">kustanttaat</t>
            <stem>kustanna-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">belønne</l>
      <mg>
         <tg>
            <t pos="V">palkita</t>
            <stem>palkitte-</stem>
            <stem>palkitten-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">berge</l>
      <mg>
         <tg>
            <t pos="V">pelastaat</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">berolige</l>
      <mg>
         <tg>
            <t pos="V">rauhottaat</t>
            <stem>rauhota-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">berøre</l>
      <mg>
         <tg>
            <t pos="V">koskeet</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="V">kosketella</t>
            <stem>koskettele-</stem>
            <stem>kosketelu-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">beslutte</l>
      <mg>
         <tg>
            <t pos="V">päättäät</t>
            <stem>päätä-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">bestemme</l>
      <mg>
         <tg>
            <t pos="V">määrätä</t>
            <stem>määrää-</stem>
            <stem>määrän-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">bestille</l>
      <mg>
         <tg>
            <t pos="V">tilata</t>
            <stem>tillaa-</stem>
            <stem>tilan-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">besvime</l>
      <mg>
         <tg>
            <t pos="V">menettyyt</t>
            <stem>menety-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">besøke</l>
      <mg>
         <tg>
            <t pos="V">kylästellä</t>
            <stem>kylästele-</stem>
            <stem>kylästel-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="V">betale</l>
      <mg>
         <tg>
            <t pos="V">maksaat</t>
         </tg>
      </mg>
   </e>
