=== giellalt/dict-nob-fkv/dtd/nobfkv.dtd
<!ELEMENT e ( lg, mg+ ) >
<!ATTLIST e src CDATA #REQUIRED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr NMTOKEN #IMPLIED >
<!ATTLIST l pos ( A | Adv | CC | CS | Det | Interj | N | Num | Phrase | Po | Pr | Pron | V ) #IMPLIED >
<!ATTLIST l t_type NMTOKEN #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >

<!ELEMENT lg ( l ) >

<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT mg ( re?, tg, syng? ) >

<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xml:lang (nob) #IMPLIED>
<!ATTLIST r id (nobfkv) #IMPLIED>

<!ELEMENT syng ( syn+ ) >
<!ELEMENT syn ( #PCDATA ) >
<!ELEMENT xhtml:script ( #PCDATA ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t val ( TV|IV ) #IMPLIED >
<!ATTLIST t pos CDATA #IMPLIED >
<!ATTLIST t src NMTOKEN #IMPLIED >
<!ATTLIST t stem CDATA #IMPLIED >
<!ATTLIST t type CDATA #IMPLIED >
<!ATTLIST t t_type ( Phrase ) #IMPLIED >
<!ATTLIST t href CDATA #IMPLIED >

<!ELEMENT tg ( re?, t+, xg* ) >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang NMTOKEN #FIXED "fkv" >
<!ATTLIST tg dial (p|j|v|pv|jv|pj) #IMPLIED >

<!ELEMENT re  ( #PCDATA )>
<!ATTLIST re
fra_ref CDATA #IMPLIED
>

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-nob-fkv/src/Phrase_nobfkv.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/nobfkv.dtd">
<r xml:lang="nob">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
          <e src="anb">
        <lg>
         <l t_type="Phrase">lete etter nåla i høystakken</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
         <t t_type="Phrase">hakkeet neulaa heinäsaurasta</t>
         <t t_type="Phrase">hakkeet äimää heinäsaurasta</t>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l t_type="Phrase">med åpne armer</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">aukkein sylin</t>
         <xg>
            <x>Han tok meg imot med åpne armer.</x>
            <xt>Hän otti minun vasthaan aukkein sylin.</xt>
         </xg>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l t_type="Phrase">med åpent sinn</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">aukkein mielin</t>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l t_type="Phrase">med nebb og klør</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">kynsin hamphain</t>
         </tg>
      </mg>
   </e>
   <e src="es">
      <lg>
         <l t_type="Phrase">dette av lasset</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">puđota matkasta</t>
            <xg>
               <x>Nå datt jeg av lasset, kan du forklare på nytt?</x>
               <xt>Nyt mie putosin matkasta, saattaisitko selittäät uuđesti?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="es">
      <lg>
         <l t_type="Phrase">ramle av lasset</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">puđota matkasta</t>
            <xg>
               <x>Nå ramlet jeg av lasset, kan du forklare på nytt?</x>
               <xt>Nyt mie putosin matkasta, saattaisitko selittäät uuđesti?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="es">
      <lg>
         <l t_type="Phrase">falle av lasset</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">puđota matkasta</t>
            <xg>
               <x>Nå falt jeg av lasset, kan du forklare på nytt?</x>
               <xt>Nyt mie putosin matkasta, saattaisitko selittäät uuđesti?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="es">
      <lg>
         <l t_type="Phrase">miste tråden</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">puđota matkasta</t>
            <xg>
               <x>Nå mistet jeg tråden, kan du forklare på nytt?</x>
               <xt>Nyt mie putosin matkasta, saattaisitko selittäät uuđesti?</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l t_type="Phrase">legge i jern</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">panna rauthoin</t>
            <xg>
               <x>Politiet la forbryteren i jern.</x>
               <xt>Pulettija pani rikolisen rauthoin.</xt>
            </xg>
         </tg>
      </mg>
   </e>
   <e src="ai">
      <lg>
         <l t_type="Phrase">og så videre</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">ja niin eđespäin</t>
            <t t_type="Phrase">ja niin poispäin</t>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l t_type="Phrase">i manns minne</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t pos="Adv">miesmuisthiin</t>
         </tg>
      </mg>
   </e>
   <e src="anb">
      <lg>
         <l t_type="Phrase">med en gang</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">yhtä mennoo</t>
         </tg>
      </mg>
   </e>
   <e src="es">
      <lg>
         <l t_type="Phrase">ikke være tørr bak ørene</l>
      </lg>
      <mg>
         <tg xml:lang="fkv">
            <t t_type="Phrase">olla korvatakuset kuivat</t>
            <xg>
               <x>Han er ikke tørr bak ørene en gang.</x>
               <xt>Hänelä ei ole korvantakusetkhaan kuivat.</xt>
            </xg>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-nob-fkv/src/num_nobfkv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r PUBLIC "-//XMLmind//DTD nobfkv//FI" "../script/nobfkv.dtd">
<?xml-stylesheet type="text/css" href="../script/nobfkv.css"?>
<r xmlns:xhtml="http://www.w3.org/1999/xhtml">
   <lics xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT,
          Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <l pos="Num" type="ord">ellevte</l>
      <mg>
         <tg>
            <t pos="Num">yhđestoista</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">en</l>
      <mg>
         <tg>
            <t pos="Num">yksi</t>
            <stem>yhđe-</stem>
            <stem>yh-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">fem</l>
      <mg>
         <tg>
            <t pos="Num">viisi</t>
            <t pos="Num">viis</t>
            <stem>viiđe-</stem>
            <stem>viit-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">femten</l>
      <mg>
         <tg>
            <t pos="Num">viisitoista</t>
            <t pos="Num">viistoista</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">femti</l>
      <mg>
         <tg>
            <t pos="Num">viiskymmentä</t>
            <t pos="Num">viisikymmentä</t>
            <stem>viisikymmene-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">fire</l>
      <mg>
         <tg>
            <t pos="Num">nelje</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num" type="ord">fjerde</l>
      <mg>
         <tg>
            <t pos="Num">neljes</t>
            <stem>neljenhee-</stem>
            <stem>neljet-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">hundre</l>
      <mg>
         <tg>
            <t pos="Num">sata</t>
            <stem>sađa-</stem>
            <stem>satta-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">ni</l>
      <mg>
         <tg>
            <t pos="Num">yhđeksen</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">seks</l>
      <mg>
         <tg>
            <t pos="Num">kuus</t>
            <stem>kuuđe-</stem>
            <stem>kuut-</stem>
         </tg>
         <tg>
            <t pos="Num">kuusi</t>
            <stem>kuuđe-</stem>
            <stem>kuut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">sekshundre</l>
      <mg>
         <tg>
            <t pos="Num">kuusisattaa</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">seksten</l>
      <mg>
         <tg>
            <t pos="Num">kuusitoista</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">seksti</l>
      <mg>
         <tg>
            <t pos="Num">kuusikymmentä</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">sekstusen</l>
      <mg>
         <tg>
            <t pos="Num">kuusituhatta</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num" type="ord">sjette</l>
      <mg>
         <tg>
            <t pos="Num">kuuđes</t>
            <stem>kuuđenne-</stem>
            <stem>kuuđet-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">sju</l>
      <mg>
         <tg>
            <t pos="Num">seittemen</t>
            <t pos="x">seittemän</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">ti</l>
      <mg>
         <tg>
            <t pos="Num">kymmenen</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num" type="ord">tiende</l>
      <mg>
         <tg>
            <t pos="Num">kymmenes</t>
            <stem>kymmenenne-</stem>
            <stem>kymmenet-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">tjue</l>
      <mg>
         <tg>
            <t pos="Num">kakskymmentä</t>
            <stem>kakskymmene-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">to</l>
      <mg>
         <tg>
            <t pos="Num">kaksi</t>
            <stem>kahđe-</stem>
            <stem>kah-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">tolv</l>
      <mg>
         <tg>
            <t pos="Num">kakstoista</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">totusen</l>
      <mg>
         <tg>
            <t pos="Num">kakstuhatta</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">tre</l>
      <mg>
         <tg>
            <t pos="Num">kolme</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">trehundre</l>
      <mg>
         <tg>
            <t pos="Num">kolmesattaa</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">tretti</l>
      <mg>
         <tg>
            <t pos="Num">kolmekymmentä</t>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">åtte</l>
      <mg>
         <tg>
            <t pos="Num">kahđeksen</t>
            <stem>kahđeksene-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">åttehundre</l>
      <mg>
         <tg>
            <t pos="Num">kahđeksensattaa</t>
            <stem>kahđeksensađa-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l pos="Num">åtti</l>
      <mg>
         <tg>
            <t pos="Num">kahđeksenkymmentä</t>
            <stem>kahđeksenkymmene-</stem>
         </tg>
      </mg>
   </e>
   <xhtml:script type="text/javascript" src="../../scripts/gt_dictionary.js"/>
</r>

=== giellalt/dict-nob-fkv/src/a4_nobfkv.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../script/nobfkv.css"?>
<!DOCTYPE r
  PUBLIC "-//XMLmind//DTD nobfkv//FI" "../script/nobfkv.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml">
   <lics>
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen at Kainun institutti, Giellatekno at UiT, Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not always
     sorted, or sorted in the wrong order. (If consistent (but wrong) sorting is
     important, use Firefox.)
     </sourcenote>
   </lics>
   <e>
      <l decl="a4">åpen</l>
      <mg>
         <tg>
            <t pos="a">auki</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="a4">beruset</l>
      <mg>
         <tg>
            <t pos="x">humalossa</t>
         </tg>
      </mg>
      <mg>
         <tg>
            <t pos="x">päissä</t>
         </tg>
      </mg>
      <syng>
         <syn>humalossa"</syn>
      </syng>
   </e>
   <e>
      <l decl="a4">forbannet</l>
      <mg>
         <tg>
            <t pos="x">pirusti</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="a4">vannskadet</l>
      <mg>
         <tg>
            <t pos="x">veđenpillaama</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="a4">kroket</l>
      <mg>
         <tg>
            <t pos="a">kippura</t>
         </tg>
      </mg>
   </e>
  <xhtml:script type="text/javascript" src="../../scripts/gt_dictionary.js" />
</r>

=== giellalt/dict-nob-fkv/src/f1_nobfkv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r PUBLIC "-//XMLmind//DTD nobfkv//FI" "../script/nobfkv.dtd">
<?xml-stylesheet type="text/css" href="../script/nobfkv.css"?>
<r xmlns:xhtml="http://www.w3.org/1999/xhtml">
   <lics xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT,
          Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted.
     </sourcenote>
   </lics>
   <e>
      <l decl="f1" pos="N">badebuks</l>
      <mg>
         <tg>
            <t pos="N">uimahousut</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">ballongbukse</l>
      <mg>
         <tg>
            <t pos="N">palonkihousut</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">barmhjertighet</l>
      <mg>
         <tg>
            <t pos="N">lauppeus</t>
            <stem>lauppeuđe-</stem>
            <stem>lauppeut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">bukse</l>
      <mg>
         <tg>
            <t pos="N">housut</t>
         </tg>
      </mg>
      <syng>
         <syn>prakut</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">båtstø</l>
      <mg>
         <tg>
            <t pos="N">valkama</t>
         </tg>
      </mg>
      <syng>
         <syn>venheensija</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">dønning</l>
      <mg>
         <tg>
            <t pos="N">siikatet</t>
            <stem>siikathee-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">fjellrype</l>
      <mg>
         <tg>
            <t pos="N">kieruna</t>
         </tg>
         <tg>
            <t pos="N">tuntuririekko</t>
            <stem>tunturirieko-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">forside</l>
      <mg>
         <tg>
            <t pos="N">etupuoli</t>
            <stem>etupuole-</stem>
            <stem>etupuol-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">gjedde</l>
      <mg>
         <tg>
            <t pos="N">hauki</t>
            <stem>haue-</stem>
            <stem>haukke-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">godhet</l>
      <mg>
         <tg>
            <t pos="N">hyvvyys</t>
            <stem>hyvvyyđe-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">harv</l>
      <mg>
         <tg>
            <t pos="N">karhii</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">hytte</l>
      <mg>
         <tg>
            <t pos="N">mökki</t>
            <stem>möki-</stem>
         </tg>
         <tg>
            <t pos="N">hyttä</t>
            <stem>hytä-</stem>
         </tg>
      </mg>
      <syng>
         <syn>mökki</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">høyberging</l>
      <mg>
         <tg>
            <t pos="N">heinänkorju</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">innberging</l>
      <mg>
         <tg>
            <t pos="N">korju</t>
         </tg>
      </mg>
      <syng>
         <syn>heinänkorju</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">issørpe</l>
      <mg>
         <tg>
            <t pos="N">hyhmä</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">krigstid</l>
      <mg>
         <tg>
            <t pos="N">sođanaika</t>
            <stem>sođanaija-</stem>
            <stem>sođanaikka-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">kvern</l>
      <mg>
         <tg>
            <t pos="N">mylly</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">mattefille</l>
      <mg>
         <tg>
            <t pos="N">mattafilleri</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">merd</l>
      <mg>
         <tg>
            <t pos="N">merta</t>
            <stem>merra-</stem>
            <stem>mertta-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">mørketid</l>
      <mg>
         <tg>
            <t pos="N">pimmeenaika</t>
            <stem>pimmeenaija-</stem>
            <stem>pimmeenaikka-</stem>
         </tg>
      </mg>
      <syng>
         <syn>kaamos</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">nise</l>
      <mg>
         <tg>
            <t pos="N">nissu</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">niste</l>
      <mg>
         <tg>
            <t pos="N">eväs</t>
            <stem>evhää-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">nonne</l>
      <mg>
         <tg>
            <t pos="N">nunna</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">renning</l>
      <mg>
         <tg>
            <t pos="N">luoma</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">rifle</l>
      <mg>
         <tg>
            <t pos="N">rikkopyssy</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">sannhet</l>
      <mg>
         <tg>
            <t pos="N">tottuus</t>
            <stem>tottuuđe-</stem>
            <stem>tottuut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">selvstendighet</l>
      <mg>
         <tg>
            <t pos="N">ittenäisyys</t>
            <stem>ittenäisyyđe-</stem>
            <stem>ittenäisyyt-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">sjørøye</l>
      <mg>
         <tg>
            <t pos="N">merirautu</t>
            <stem>merirauđu-</stem>
            <stem>merirauttu-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">skare</l>
      <mg>
         <tg>
            <t pos="N">roustet</t>
            <stem>rousthee-</stem>
         </tg>
         <tg>
            <t pos="N">kerstet</t>
            <stem>kersthee-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">skinnfell</l>
      <mg>
         <tg>
            <t pos="N">rouko</t>
            <stem>rouo-</stem>
            <stem>roukko-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">snelle</l>
      <mg>
         <tg>
            <t pos="N">kela</t>
            <stem>kella-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">stillhet</l>
      <mg>
         <tg>
            <t pos="N">hiljaisuus</t>
            <stem>hiljaisuuđe-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">stoppenål</l>
      <mg>
         <tg>
            <t pos="N">toppineula</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">tavle</l>
      <mg>
         <tg>
            <t pos="N">taulu</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">tilje</l>
      <mg>
         <tg>
            <t pos="N">telju</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">timelønn</l>
      <mg>
         <tg>
            <t pos="N">tiimapalkka</t>
            <stem>tiimapalka-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">trekullgrop</l>
      <mg>
         <tg>
            <t pos="N">sysihauta</t>
            <stem>sysihauđa-</stem>
            <stem>sysihautta-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">trofasthet</l>
      <mg>
         <tg>
            <t pos="N">uskolisuus</t>
            <stem>uskolisuuđe-</stem>
            <stem>uskolisuut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">tromme</l>
      <mg>
         <tg>
            <t pos="N">trumma</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">ugle</l>
      <mg>
         <tg>
            <t pos="N">ykla</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">veiledning</l>
      <mg>
         <tg>
            <t pos="N">opastus</t>
            <stem>opastukse-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">vindstille</l>
      <mg>
         <tg>
            <t pos="N">tyven</t>
            <stem>tyvene-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">åre</l>
      <mg>
         <tg>
            <t pos="N">airo</t>
            <stem>airro-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">ødemark</l>
      <mg>
         <tg>
            <t pos="N">korpi</t>
            <stem>korve-</stem>
            <stem>korppe-</stem>
         </tg>
      </mg>
   </e>
   <xhtml:script type="text/javascript" src="../../scripts/gt_dictionary.js"/>
</r>
